### ISSUE TITLE
你这个是python2的代码嘛？

### ISSUE THREAD

**Issue by lvouran** [tonyupup/BloomFilter#2]
我改成python3后，判断是否存在的时候总是false，只改动了 has_keys方法和Unicode的类型判断，，能否方便改成python3提交一下呢？谢谢了

**Comment by tonyupup** [comment]
python3不能使用是因为在python3中map为惰性计算，请将源码中使用map函数地方使用list(map(***)) 替换。

**Comment by lvouran** [comment]
语法的地方之前已经改过了，python3，map返回的是迭代器，，主要是没搞明白，存好之后用exist方法判断是否存在的时候，返回总是false
